spring.application.name=sb-ecom

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:test

project.image=src/main/resources/images
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=update


spring.app.jwtSecret=idKoluIErcZ2rn+prYzkW9puhYBQJ0Ka4tj7rpF5fcM=
spring.app.jwtExpirationMS=300000

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.ecommerce.project=DEBUG